news/urls.py
from django.urls import path
from .views import *
app_name = 'news'
urlpatterns = [
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/login/', SiteLoginView.as_view(), name='login'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/logout/', SiteLogoutView.as_view(), name='logout'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/password/change/', SitePasswordChangeView.as_view(), name='password_change'),
    path('', posts_list, name='posts_list_url'),
    path('post/create/', PostCreate.as_view(), name='post_create_url'),
    path('post/<str:slug>/', PostDetail.as_view(), name='post_detail_url'),
    path('post/<str:slug>/update/', PostUpdate.as_view(), name='post_update_url'),
    path('post/<str:slug>/delete/', PostDelete.as_view(), name='post_delete_url'),
    path('tags/', tags_list, name='tags_list_url'),
    path('tags/create/', TagCreate.as_view(), name='tag_create_url'),
    path('tags/<str:slug>/', TagDetail.as_view(), name='tag_detail_url'),
    path('tags/<str:slug>/update/', TagUpdate.as_view(), name='tag_update_url'),
    path('tags/<str:slug>/delete/', TagDelete.as_view(), name='tag_delete_url')
]

news_site/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.urls import include
from .views import redirect_blog
from django.conf.urls.static import static

urlpatterns = [
    path('', redirect_blog),
    path('admin/', admin.site.urls),
    path('news/', include('news.urls', namespace='news')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.shortcuts import reverse
from django.utils.text import slugify
from time import time
from django.dispatch import Signal
from .utils import send_activation_notification, get_timestamp_path
from ckeditor.fields import RichTextField
# Create your models here.

user_registrated = Signal(providing_args=['instance'])


def user_registrated_dispatcher(sender, **kwargs):
    send_activation_notification(kwargs['instance'])


user_registrated.connect(user_registrated_dispatcher)


def gen_slug(s):
    new_slug = slugify(s, allow_unicode=True)
    return new_slug + '-' + str(int(time()))


class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True, verbose_name='Is activated?')
    send_messages = models.BooleanField(default=True, verbose_name='Send notifications about new comments?')

    def delete(self, *args, **kwargs):
        for post in self.post_set.all():
            post.delete()
        super().delete(*args, **kwargs)

    class Meta(AbstractUser.Meta):
        swappable = 'AUTH_USER_MODEL'


class Post(models.Model):
    title = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, blank=True, unique=True)
    body = RichTextField(blank=True, null=True, db_index=True)
    tags = models.ManyToManyField('Tag', blank=True, related_name='posts')
    author = models.ForeignKey(AdvUser, default=1, on_delete=models.CASCADE, verbose_name='Posted by')
    image = models.ImageField(blank=True, upload_to=get_timestamp_path, verbose_name='Image')
    date_pub = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True, db_index=True, verbose_name='List in?')
    is_moderation = models.NullBooleanField(default=False)

    def get_absolute_url(self):
        return reverse('news:post_detail_url', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('news:post_update_url', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('news:post_delete_url', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = gen_slug(self.title)
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        for ai in self.additionalimage_set.all():
            ai.dlete()
        super().delete(*args, **kwargs)

    class Meta:
        ordering = ['-date_pub']

    def __str__(self):
        return self.title


class AdditionalImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Post')
    image = models.ImageField(upload_to=get_timestamp_path, verbose_name='Image')

    class Meta:
        verbose_name_plural = 'Additional illustrations'
        verbose_name = 'Additional illustration'


class Tag(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True)

    def get_absolute_url(self):
        return reverse('news:tag_detail_url', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('news:tag_update_url', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('news:tag_delete_url', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title

news/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import AdvUser, Tag, Post
from django.contrib.auth import password_validation
from .models import user_registrated


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Email')
    password1 = forms.CharField(label='Password',
                                widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Confirm password',
                                widget=forms.PasswordInput,
                                help_text='Confirm your password')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError(
                'Password confirmation error', code='password_mismatch')}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registrated.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'send_messages')


class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Email')

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name', 'send_messages')


class TagForm(forms.ModelForm):

    class Meta:
        model = Tag
        fields = ['title', 'slug']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'})
        }

    def clean_slug(self):
        new_tag = self.cleaned_data['slug'].lower()

        if new_tag == 'create':
            raise ValidationError('Slug may not be "create"')
        if Tag.objects.filter(slug__exact=new_tag).count():
            raise ValidationError('Slug must be unique. We have "{}" slug already'.format(new_tag))
        return new_tag


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'slug', 'image', 'body', 'tags', 'author']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'tags': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }

    def clean_slug(self):
        new_slug = self.cleaned_data['slug'].lower()

        if new_slug == 'create':
            raise ValidationError('Slug may not be "create"')
        return new_slug

news/views.py
from django.views.generic import UpdateView
from django.views.generic.edit import DeleteView
from django.contrib.auth import logout
from django.contrib import messages
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.views.generic import View, CreateView
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from .models import AdvUser, Post, Tag
from .utils import *
from .forms import RegisterUserForm, ChangeUserInfoForm, TagForm, PostForm
from django.core.signing import BadSignature


# Create your views here.

class SiteLoginView(LoginView):
    template_name = 'news/login.html'


class SiteLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'news/logout.html'


@login_required
def profile(request):
    posts = Post.objects.filter(author=request.user.pk)
    context = {'posts': posts}
    return render(request, 'news/profile.html', context)


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = AdvUser
    template_name = 'news/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('news:profile')
    success_message = 'Personal data of user was changed'

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class SitePasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'news/password_change.html'
    success_url = reverse_lazy('news:profile')
    success_message = 'Password of user was changed'


class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'news/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('news:register_done')


class RegisterDoneView(TemplateView):
    template_name = 'news/register_done.html'


class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name = 'news/delete user.html'
    success_url = reverse_lazy('news:posts_list_url')

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'User was deleted')
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'news/bad_signature.html')
    user = get_object_or_404(AdvUser, username=username)
    if user.is_activated:
        template = 'news/user_is_activated.html'
    else:
        template = 'news/activation_done.html'
        user.is_active = True
        user.is_activated = True
        user. save()
    return render(request, template)


def posts_list(request):
    search_query = request.GET.get('search', '')
    if search_query:
        posts = Post.objects.filter(Q(title__icontains=search_query) | Q(body__icontains=search_query))
        # posts = Post.objects.filter(Q(title__icontains=search_query) | Q(body__icontains=search_query) | Q(is_moderation=True))
    else:
        posts = Post.objects.all()
        # posts = Post.objects.filter(is_moderation=True)
    paginator = Paginator(posts, 2)
    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)
    is_paginated = page.has_other_pages()
    if page.has_previous():
        prev_url = '?page={}'.format(page.previous_page_number())
    else:
        prev_url = ''
    if page.has_next():
        next_url = '?page={}'.format(page.next_page_number())
    else:
        next_url = ''
    return render(request, 'news/index.html',
                  context={
                      'page_object': page,
                      'is_paginated': is_paginated,
                      'prev_url': prev_url,
                      'next_url': next_url
                  })


class PostDetail(ObjectDetailMixin, View):
    model = Post
    template = 'news/post_detail.html'


class PostCreate(LoginRequiredMixin, ObjectCreateMixin, View):
    model_form = PostForm
    template = 'news/post_create.html'
    raise_exception = True
    # post = Post(is_moderation=False)
    # post.save()


class PostUpdate(LoginRequiredMixin, ObjectUpdateMixin, View):
    model = Post
    model_form = PostForm
    template = 'news/post_update_form.html'
    raise_exception = True


class PostDelete(LoginRequiredMixin, ObjectDeleteMixin, View):
    model = Post
    template = 'news/post_delete_form.html'
    redirect_url = 'posts_list_url'
    raise_exception = True


class TagDetail(ObjectDetailMixin, View):
    model = Tag
    template = 'news/tag_detail.html'


class TagCreate(LoginRequiredMixin, ObjectCreateMixin, View):
    model_form = TagForm
    template = 'news/tag_create.html'
    raise_exception = True


class TagUpdate(LoginRequiredMixin, ObjectUpdateMixin, View):
    model = Tag
    model_form = TagForm
    template = 'news/tag_update_form.html'
    raise_exception = True


class TagDelete(LoginRequiredMixin, ObjectDeleteMixin, View):
    model = Tag
    template = 'news/tag_delete_form.html'
    redirect_url = 'tags_list_url'
    raise_exception = True


def tags_list(request):
    tags = Tag.objects.all()
    return render(request, 'news/tags_list.html', context={'tags': tags})

news/templates/news/activation_done.html
{% extends "base.html" %}
{% block title %}Activation completed{% endblock %}
{% block content %}
    <h2>Activation</h2>
    <p>User was activated</p>
    <p><a href="{% url 'news:login' %}">Enter the sate</a></p>
{% endblock %}

news/templates/news/base_news.html
{%extends 'base.html'%}
{% block admin-panel %}
    <div class="btn-group">
      <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Create
      </button>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="{% url 'news:post_create_url' %}">Post</a>
        <a class="dropdown-item" href="{% url 'news:tag_create_url' %}">Tag</a>
      </div>
    </div>
    <a href="{{ admin_object.get_update_url }}" class="btn btn-light update" style="{% if detail %}display:block;{% endif %}">Update</a>
    <a href="{{ admin_object.get_delete_url }}" class="btn btn-danger delete" style="{% if detail %}display:block;{% endif %}">Delete</a>
{% endblock %}

news/templates/news/delete user.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %} User delete {% endblock %}
{% block content %}
    <h2>User delete {{ object.username }}</h2>
    <form method="post">
        {% csrf_token %}
        {% buttons submit='Delete' %}{% endbuttons %}
    </form>
{% endblock %}

news/templates/news/login.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}Login{% endblock %}
{% block content %}
    <h2>Login</h2>
    {% if user.is_authenticated%}
        <p> You are already signed in. </p>
    {% else %}
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form layout='horizontal' %}
            <input type="hidden" name="next" value="{{ next }}">
            {% buttons submit='Login' %}{% endbuttons %}
        </form>
    {% endif %}
{% endblock %}

news/templates/news/logout.html
{% extends "base.html" %}
{% block title %} Logout {% endblock %}
{% block content %}

<h2>Logout</h2>
<p>You have successfully logged out of the site.</p>
{% endblock %}

news/templates/news/password_change.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Change password{% endblock %}
{% block content %}
    <h2>Password change of {{ user.username }}</h2>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit='Change password' %}{% endbuttons %}
    </form>
{% endblock %}

news/templates/news/post_create.html
{% extends 'news/base_news.html' %}

{% block title %}
    Post Create - {{ block.super }}
{% endblock %}

{% block content %}
    <form action="{% url 'news:post_create_url' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            {%include 'news/includes/form_template.html'%}
        {% endfor %}
        {{ form.media }}
        <button type="submit" class="btn btn-primary">Create Post</button>
    </form>
{% endblock %}

news/templates/news/post_delete_form.html
{% extends 'news/base_news.html' %}

{% block title %}
    Delete Post "{{ post.title|title }}" - {{ block.super }}
{% endblock %}

{% block content %}
    <form action="{{post.get_delete_url}}" method="post">
        {% csrf_token %}
        <h3>Are yuo sure what you want delete "{{ post.title }}" post ?</h3>
        <a href="{{ post.get_absolute_url }}">Back</a>
        <button class="btn btn-danger">Delete</button>
    </form>
{% endblock %}

news/templates/news/post_update_form.html
{% extends 'news/base_news.html' %}
{% block title %}
    Edit Post "{{ post.title }}" - {{ block.super }}
{% endblock %}

{% block content %}
    <form action="{{ post.get_update_url }}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            {%include 'news/includes/form_template.html'%}
        {% endfor %}
        {{ form.media }}
        <button type="submit" class="btn btn-primary">Update Post</button>
    </form>
{% endblock %}

news/templates/news/register_user.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title  %} Registration {% endblock %}
{% block content %}
    <h2> New user registration </h2>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit='Registration' %}{% endbuttons %}
    </form>
{% endblock %}

news/templates/news/tag_create.html
{% extends 'news/base_news.html' %}

{% block title %}
    Tag Create - {{ block.super }}
{% endblock %}

{% block content %}

    <form action="{% url 'news:tag_create_url' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            {%include 'news/includes/form_template.html'%}
        {% endfor %}
        <button type="submit" class="btn btn-primary">Create Tag</button>
    </form>

{% endblock %}

news/templates/news/tag_delete_form.html
{% extends 'news/base_news.html' %}

{% block title %}
    Delete Tag "{{ tag.title|title }}" - {{ block.super }}
{% endblock %}

{% block content %}
    <form action="{{tag.get_delete_url}}" method="post">
        {% csrf_token %}
        <h3>Are yuo sure what you want delete "{{ tag.title }}" tag ?</h3>
        <a href="{{ tag.get_absolute_url }}">Back</a>
        <button class="btn btn-danger">Delete</button>
    </form>
{% endblock %}

news/templates/news/tag_detail.html
{%extends 'news/base_news.html'%}
{%block title%}
    {{tag.title}}-{{block.super}}
{%endblock%}
{%block content%}
    <h1 class="mt-5"> Posts with "{{tag.title|title}}" tag:</h1>
    {%for post in tag.posts.all%}
        {%include 'news/includes/post_card_template.html'%}
    {%endfor%}
{%endblock%}

news/templates/news/tag_update_form.html
{% extends 'news/base_news.html' %}

{% block title %}
   Edit Tag "{{ tag.title }}" - {{ block.super }}
{% endblock %}

{% block content %}

    <form action="{{tag.get_update_url}}" method="post">
        {% csrf_token %}
        {% for field in form %}
            {%include 'news/includes/form_template.html'%}
        {% endfor %}
        <button type="submit" class="btn btn-primary">Update Tag</button>

    </form>
{% endblock %}