news/urls.py
from django.urls import path
from .views import *
app_name = 'news'
urlpatterns = [
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/login/', SiteLoginView.as_view(), name='login'),
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/logout/', SiteLogoutView.as_view(), name='logout'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/password/change/', SitePasswordChangeView.as_view(), name='password_change'),
    path('', posts_list, name='posts_list_url'),
    path('post/create/', PostCreate.as_view(), name='post_create_url'),
    path('post/<str:slug>/', PostDetail.as_view(), name='post_detail_url'),
    path('post/<str:slug>/update/', PostUpdate.as_view(), name='post_update_url'),
    path('post/<str:slug>/delete/', PostDelete.as_view(), name='post_delete_url'),
    path('tags/', tags_list, name='tags_list_url'),
    path('tags/create/', TagCreate.as_view(), name='tag_create_url'),
    path('tags/<str:slug>/', TagDetail.as_view(), name='tag_detail_url'),
    path('tags/<str:slug>/update/', TagUpdate.as_view(), name='tag_update_url'),
    path('tags/<str:slug>/delete/', TagDelete.as_view(), name='tag_delete_url')
]

news_site/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.urls import include
from .views import redirect_blog
from django.conf.urls.static import static

urlpatterns = [
    path('', redirect_blog),
    path('admin/', admin.site.urls),
    path('news/', include('news.urls', namespace='news')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        {% bootstrap_css %}
        <link rel="stylesheet" href="{% static "css/style.css" %}">
        <title>{% block title %}Title{% endblock %}</title>
        {% bootstrap_javascript  %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="background-color: #e3f2fd;">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'news:posts_list_url' %}">Posts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'news:tags_list_url' %}">Tags</a>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'news:register' %}">Registration</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown"
                    href="#" role="button" aria-haspopup="true"
                    aria-expanded="false">Profile</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'news:profile_change' %}">Account</a>
                        <a class="dropdown-item" href="{% url 'news:password_change' %}">Change password</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'news:profile' %}">My posts</a>
                        <a class="dropdown-item" href="{% url 'news:logout' %}">Logout</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'news:profile_delete' %}">Delete account</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'news:login' %}">Login</a></li>
                {% endif %}
            </ul>
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </nav>
        <div class="container mt-5">
            <div class="row">
                <div class="col-6 offset-md-2">
                    {% block content %}
                        Some content
                    {% endblock %}
                    {% if is_paginated%}
                        <nav aria-label="...">
                            <ul class="pagination">
                                <li class="page-item {% if not prev_url %}disabled{% endif %}">
                                  <a class="page-link" href="{{ prev_url }}" tabindex="-1" aria-disabled="true">&laquo;</a>
                                </li>
                                {% for n in page_object.paginator.page_range %}
                                    {% if page_object.number == n %}
                                        <li class="page-item active"><a class="page-link" href="?page={{ n }}">{{n}}</a></li>
                                    {% elif n > page_object.number|add:-3 and n < page_object.number|add:3%}
                                        <li class="page-item"><a class="page-link" href="?page={{ n }}">{{n}}</a></li>
                                    {% endif %}
                                {% endfor %}
                                {% if next_url %}
                                    <li class="page-item">
                                      <a class="page-link" href="{{ next_url }}">&raquo;</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    {% endif %}
                </div>
            </div>
        </div>
        {% if request.user.is_authenticated and request.user.is_staff %}
            <div class="admin-panel align-item-center">
                <a href="/admin" class="btn btn-outline-info">Admin</a>
                {% block admin-panel %}{% endblock %}
            </div>
        {% endif %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>